project_name: wait-for-tcp
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wait-for-tcp/main.go
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
dockers:
  - id: wait-for-tcp
    goos: linux
    goarch: amd64
    goamd64: "v2"
    ids:
      - wait-for-tcp
    image_templates:
      - ghcr.io/containeroo/wait-for-tcp:latest
      - ghcr.io/containeroo/wait-for-tcp:{{ trimprefix .Tag "v" }}
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/wait-for-tcp
      - --label=org.opencontainers.image.source=https://github.com/containeroo/wait-for-tcp
      - --label=org.opencontainers.image.version={{ trimprefix .Version "v" }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
    extra_files:
      - go.mod
      - cmd
