project_name: wait-for-tcp
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wait-for-tcp-build
    main: ./cmd/wait-for-tcp/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - ghcr.io/containeroo/wait-for-tcp:{{ timprefix .Tag "v" }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - cmd
  - image_templates:
      - ghcr.io/containeroo/wait-for-tcp:{{ trimprefix.Tag "v" }}-arm64v8
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - go.mod
      - cmd
docker_manifests:
  - name_template: ghcr.io/containeroo/wait-for-tcp:{{ trimprefix .Tag "v" }}
    image_templates:
      - ghcr.io/containeroo/wait-for-tcp:{{ trimprefix .Tag "v" }}-amd64
      - ghcr.io/containeroo/wait-for-tcp:{{ trimprefix .Tag }v" }}-arm64v8
